// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BlobStorageTest.Client.Models
{
    using BlobStorageTest.Client;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for LeaseStatusType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LeaseStatusType
    {
        [EnumMember(Value = "locked")]
        Locked,
        [EnumMember(Value = "unlocked")]
        Unlocked
    }
    internal static class LeaseStatusTypeEnumExtension
    {
        internal static string ToSerializedValue(this LeaseStatusType? value)
        {
            return value == null ? null : ((LeaseStatusType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this LeaseStatusType value)
        {
            switch( value )
            {
                case LeaseStatusType.Locked:
                    return "locked";
                case LeaseStatusType.Unlocked:
                    return "unlocked";
            }
            return null;
        }

        internal static LeaseStatusType? ParseLeaseStatusType(this string value)
        {
            switch( value )
            {
                case "locked":
                    return LeaseStatusType.Locked;
                case "unlocked":
                    return LeaseStatusType.Unlocked;
            }
            return null;
        }
    }
}
