// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator 1.0.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace blob-storage.Models
{

    /// <summary>
    /// Defines values for PublicAccessType.
    /// </summary>
    public static class PublicAccessType
    {
        public const string Container = "container";
        public const string Blob = "blob";
    }
}

